---
abstract: 'Usergrid Perl Client'
author:
  - 'Anuradha Weeraman <anuradha@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141170'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Usergrid-Client
provides:
  Usergrid::Client:
    file: lib/Usergrid/Client.pm
    version: '0.22'
  Usergrid::Collection:
    file: lib/Usergrid/Collection.pm
  Usergrid::Entity:
    file: lib/Usergrid/Entity.pm
  Usergrid::Request:
    file: lib/Usergrid/Request.pm
requires:
  JSON: '0'
  Log::Log4perl: '0'
  Moose: '0'
  REST::Client: '0'
  URI::Template: '0'
  namespace::autoclean: '0'
resources:
  license: http://www.apache.org/licenses/LICENSE-2.0.txt
version: '0.22'
